# Generated by Django 2.1.3 on 2018-12-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_1',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_2',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_3',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_4',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_5',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
